cache: fix race condition in interprocess locking
The database lock was incorrectly released too early, causing
exceptions with this callstack:

  File "jolt/cache.py", line 2084, in _lock_artifact_interprocess
    self._db_delete_lock(db, artifact.identity)
  File "jolt/cache.py", line 1386, in _db_delete_lock
    db.commit()
sqlite3.OperationalError: database is locked

Signed-off-by: Robert Andersson <robert.m.andersson@atlascopco.com>